citys_list = {
    "Altamira": 1,
    "Americana": 0,
    "Angra Dos Reis": 0,
    "Aracaju": 0,
    "Araraquara": 0,
    "Araxá": 0,
    "Balneário Camboriú": 0,
    "Barueri": 1,
    "Bauru": 1,
    "Belém": 1,
    "Belo Horizonte": 1,
    "Blumenau": 0,
    "Brasília": 0,
    "Caçapava": 1,
    "Campina Grande": 0,
    "Campinas": 0,
    "Campo Grande": 1,
    "Campos dos Goytacazes": 1,
    "Canela": 0,
    "Cascavel": 0,
    "Caxias Do Sul": 0,
    "Chapecó": 1,
    "Confins": 1,
    "Contagem": 0,
    "Cotia": 0,
    "Cuiabá": 0,
    "Curitiba": 0,
    "Feira De Santana": 0,
    "Florianópolis": 0,
    "Fortaleza": 1,
    "Foz Do Iguaçu": 0,
    "Franca": 0,
    "Goiânia": 0,
    "Gravataí": 0,
    "Guarapuava": 1,
    "Guaratinguetá": 0,
    "Guarulhos": 1,
    "Hortolândia": 1,
    "Indaiatuba": 1,
    "Ipatinga": 1,
    "Itaquaquecetuba": 0,
    "Ivoti": 0,
    "Jaboatão Dos Guararapes": 1,
    "Jacareí": 1,
    "João Pessoa": 1,
    "Joinville": 0,
    "Juiz De Fora": 0,
    "Jundiaí": 0,
    "Lauro De Freitas": 0,
    "Londrina": 0,
    "Luís Eduardo Magalhães": 1,
    "Macapá": 0,
    "Manaus": 0,
    "Maricá": 0,
    "Marília": 1,
    "Maringá": 0,
    "Mogi Das Cruzes": 1,
    "Montes Claros": 0,
    "Natal": 1,
    "Nova Iguaçu": 1,
    "Nova Lima": 1,
    "Novo Hamburgo": 0,
    "Olinda": 1,
    "Osasco": 1,
    "Palhoça": 0,
    "Palmas": 0,
    "Parauapebas": 0,
    "Pelotas": 0,
    "Petrolina": 1,
    "Petrópolis": 1,
    "Piracicaba": 1,
    "Poá": 1,
    "Ponta Grossa": 0,
    "Porto Alegre": 0,
    "Porto Velho": 0,
    "Recife": 1,
    "Ribeirão Preto": 0,
    "Rio De Janeiro": 1,
    "Rio Verde": 0,
    "Rondonópolis": 0,
    "Salvador": 0,
    "Santa Maria": 0,
    "Santarém": 0,
    "Santo André": 0,
    "Santos": 1,
    "São Bernardo Do Campo": 0,
    "São Carlos": 0,
    "São José Do Rio Preto": 1,
    "São José Dos Campos": 1,
    "São Luís": 0,
    "São Paulo ZL": 1,
    "São Paulo ZO": 1,
    "São Paulo ZS": 1,
    "Senador Canedo": 0,
    "Sete Lagoas": 0,
    "Sinop": 0,
    "Sobral": 0,
    "Sorocaba": 1,
    "Sorriso": 0,
    "Suzano": 1,
    "Taubaté": 1,
    "Teresina": 0,
    "Tremembé": 1,
    "Tubarão": 0,
    "Uberaba": 0,
    "Uberlândia": 1,
    "Uruguaiana": 0,
    "Vila Velha": 0,
    "Vitória": 1,
    "Volta redonda": 1,
    "Votorantim": 1
}
